---
abstract: 'Simple REST client for HBase'
author:
  - 'Bosko Devetak <bosko.devetak@gmail.com>'
build_requires:
  Test::Fatal: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HBase-JSONRest
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dumper: 0
  HTTP::Tiny: 0
  JSON::XS: 0
  MIME::Base64: 0
  Time::HiRes: 0
  URI::Escape: 0
  perl: 5.006
version: 0.004
